Docs update new loss functions and examples
microsoft/BackwardCompatibilityML pull request #65
Opened 2020-11-11 02:15 UTC by jlema

- Added new loss functions to and examples to docs
- Updated docstrings to reflect binary cross entropy loss naming
- Updated auto-generated docs from docstrings
- Fixed sphinx doc build warnings

2020-11-11 18:58 UTC, nushib approved these changes

2020-11-12 21:13 UTC, Nking92 approved these changes

2020-11-12 21:20 UTC, ilmarinen approved these changes
@jlema +1

2020-11-12 21:34 UTC, KathleenW1 requested changes
Lowercase "cross entropy" in documentation's non-code running text  (Ideally, "cross-entropy" should be hyphenated throughout all documentation; does introducing the hyphenation now create inconsistency with earlier documentation?)

2020-11-13 01:32 UTC, KathleenW1 approved these changes

2020-11-13 01:40 UTC, ilmarinen approved these changes
@jlema +1 looks good.

2020-11-13 01:42 UTC, merged