PR to add dropdowns, and miscellaneous changes discussed previously
microsoft/BackwardCompatibilityML pull request #8
Opened 2020-10-06 23:13 UTC by ilmarinen

<img width="616" alt="ui-dropdowns-colors" src="https://user-images.githubusercontent.com/680818/95269540-731fb200-07ee-11eb-93f7-7de8b3726790.png">

1. Added dropdowns with checkboxes for the data selector.
2 Changed the colors per the discussion.
3. Added a selected model details component.
4. Added the dotted line indicating h1 performance.
5. Added the legend to the Venn diagram.

Note that the alignment, component tile shading, venn diagram instance numbers etc. have not yet been implemented. Those will come next.

And I will be leaving the layout till last.

2020-10-07 18:24 UTC, nushib approved these changes

2020-10-08 15:39 UTC, jlema requested changes
From a new environment, checked out the dropdowns branch and installed everything from scratch.

Ran bcbinary_cross_entropy notebook, and I'm getting **ImportError: cannot import name 'training_binary'**

The PR doesn't seem to include the **training_binary** folder under **backwardcompatibilityml/helpers** - https://github.com/microsoft/BackwardCompatibilityML/tree/b164a160a46da1efdc436350b231968c2dec6a33/backwardcompatibilityml/helpers

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ab92fc8999d8> in <module>
     15 import backwardcompatibilityml.scores as scores
     16 from backwardcompatibilityml.helpers import training
---> 17 from backwardcompatibilityml.helpers import training_binary
     18 from backwardcompatibilityml.helpers import utils
     19 from backwardcompatibilityml.widget.compatibility_analysis import CompatibilityAnalysis

ImportError: cannot import name 'training_binary'

2020-10-08 17:03 UTC, jlema commented
Ok created issue to track outdated notebooks error (#9) which will be fixed on a future PR. Approving.

2020-10-08 17:03 UTC, jlema approved these changes

2020-10-08 17:05 UTC, merged