Info tooltips (Incomplete)
microsoft/BackwardCompatibilityML pull request #81
Opened 2020-11-19 00:25 UTC by Nking92

Adds help tooltips to the charts in the widget.

Currently, the tooltips for the venn diagram legend have still not been implemented. I'm planning to wait until clickable legend https://github.com/microsoft/BackwardCompatibilityML/pull/78 is merged. The legend will need to be extracted from the d3 graph so I can add tooltips there.

For issue https://github.com/microsoft/BackwardCompatibilityML/issues/39

![image](https://user-images.githubusercontent.com/1587757/99604549-96777880-29ba-11eb-869a-68c3fd359a3c.png)

2020-11-20 00:14 UTC, jlema requested changes
Functionally the tooltips are great. Thank you.

The light blue color and smallish icon text make it hard to know what they are supposed to do, 

Could you please change them to black outline and maybe 1.5 to 2 times the current size as per the spec?

![image](https://user-images.githubusercontent.com/9736891/99739697-2e8c6500-2a82-11eb-90f0-39fabfb80bf0.png)

2020-11-20 19:52 UTC, Nking92 commented
Icon now looks like this after latest change
![image](https://user-images.githubusercontent.com/1587757/99843698-d0fe2400-2b26-11eb-8cca-2b49c6994b98.png)

2020-11-20 21:47 UTC, nushib approved these changes

2020-11-20 21:55 UTC, jlema approved these changes

2020-11-20 22:03 UTC, ilmarinen approved these changes

2020-11-25 02:03 UTC, Nking92 commented
Added tooltips to the Venn diagram legend. It required a significant rewrite of the Venn diagram code. The legend was refactored to be in the DOM instead of being SVG. Some additional refactoring was required to make d3 and React share their state nicely.

There is still some work to be done to fix some styling. For example, the diagram is now too large and overflows past the histogram. However, the general functionality should be working at this point.

@jlema @ilmarinen please play with it and let me know if it works like you expect.

![image](https://user-images.githubusercontent.com/1587757/100172935-45fe9000-2e7e-11eb-8327-61511549622c.png)

2020-11-30 17:49 UTC, ilmarinen requested changes
Noticed some issues with the alignment / size between the panels for the Venn Diagram and the Distribution of Incompatible points. See the attached image. The place where it is visible is at the bottom of each panel.
<img width="756" alt="Screen Shot 2020-11-30 at 9 47 51 AM" src="https://user-images.githubusercontent.com/680818/100645289-51741000-32f1-11eb-9500-d4bc45612a5a.png">
<img width="753" alt="Screen Shot 2020-11-30 at 9 47 10 AM" src="https://user-images.githubusercontent.com/680818/100645308-5638c400-32f1-11eb-8699-e088c98c8b39.png">

2020-11-30 17:52 UTC, ilmarinen commented on widget/IntersectionBetweenModelErrors.tsx
> +        <div className="plot-title-row">
Would it be possible to abstract away the Legend and its tooltips into its own component? VennLegend or something? You can leave it in the same file and put it near the top.

Then this part of the code could be simplified to just have the `<VennLegend />` and its associated props and methods set on it.

2020-11-30 17:54 UTC, ilmarinen commented on widget/IntersectionBetweenModelErrors.tsx
> +  intersectionFill: string
Do we really need these values of the fills in here? Can they not be derived from the `regionSelected` and perhaps other state information?

I'd suggest not directly putting style information within the state. Instead state should conceptually be about the logical state of the component ... i.e. what region is selected or what data is being shown etc. There should then be functions that we can pass that info into which will then derive style properties like fill color etc.

2020-11-30 21:53 UTC, jlema requested changes
Please note that the alignment issues are a bit different on the dev harness (e.g. bottom of Venn diagram does -not- seem to be misaligned.) See before and after clicking data point in scatter plot screenshots below.

![image](https://user-images.githubusercontent.com/9736891/100670315-86915a00-3313-11eb-9817-297e12f6d437.png)

2020-12-01 21:58 UTC, Nking92 commented
The legend has been refactored and the alignment issues have been fixed. There's still an extra space between the plot title and the scatter plot that only appears in the Jupyter environment. I haven't been able to figure out exactly why it's happening yet.

![image](https://user-images.githubusercontent.com/1587757/100801710-37aff700-33dd-11eb-9b7d-af0437ce11f8.png)

2020-12-01 23:07 UTC, ilmarinen approved these changes
@Nking92 +1 Looks great!

2020-12-01 23:15 UTC, jlema requested changes
I think I found a regression - when I click on any of the sections of the Venn diagram and then on one of the columns of the histogram, the Venn should reset its selections but it's not doing it anymore.

![image](https://user-images.githubusercontent.com/9736891/100807929-07ba2100-33e8-11eb-8a85-7883df6c961c.png)

2020-12-03 18:41 UTC, jlema approved these changes

2020-12-03 19:06 UTC, merged