Documentation for using the widget
microsoft/BackwardCompatibilityML pull request #84
Opened 2020-12-01 02:19 UTC by Nking92

Rough draft of the documentation for using the widget. For issue https://github.com/microsoft/BackwardCompatibilityML/issues/15

2020-12-01 18:24 UTC, KathleenW1 commented on docs/backwardcompatibilityml/topics/using_the_compatibility_analysis_widget.rst
> +resnet18 with the following 6 layer network using the cifar10 dataset::
Change "6 layer" to "six-layer."

2020-12-01 18:26 UTC, KathleenW1 commented on docs/backwardcompatibilityml/topics/using_the_compatibility_analysis_widget.rst
> +resnet18 with the following 6 layer network using the cifar10 dataset::
Change "6 layer" to "six-layer."

2020-12-01 18:35 UTC, KathleenW1 commented on docs/backwardcompatibilityml/topics/using_the_compatibility_analysis_widget.rst
> +and the green region represents error made only by the old model. The histogram breaks down incompatible data points by class.
Add an "s" to "error."

2020-12-01 18:38 UTC, KathleenW1 commented on docs/backwardcompatibilityml/topics/using_the_compatibility_analysis_widget.rst
> +and ``get_instance_image_by_id``, that make the data shown in the table more descriptive.
Change "that" to "which."

2020-12-01 18:40 UTC, KathleenW1 reviewed
Several minor edits indicated in in-line comments.

2020-12-01 22:45 UTC, jlema requested changes

2020-12-01 22:45 UTC, jlema commented on docs/backwardcompatibilityml/topics/using_the_compatibility_analysis_widget.rst
> +make a sweep of the possible values for |lambda|:sub:`c` and show a visualization of the
Please mention that it also sweeps over the two selected loss functions.

2020-12-03 20:34 UTC, jlema approved these changes

2020-12-03 20:48 UTC, KathleenW1 approved these changes

2020-12-03 23:27 UTC, nushib approved these changes

2020-12-03 23:46 UTC, merged